{% set name = "pytest-describe" %}
{% set version = "2.2.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pytest-describe/pytest_describe-2.2.1.tar.gz
  sha256: eb59307333508d700082a4a8aadba0f874f02c73602f7113071b0b41bfe183b7

build:
  skip: true  # [py<37]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - pytest >=4.6,<9

test:
  requires:
    - pytest-cov
    - pip
  source_files:
    - test
  imports:
    - pytest_describe
  commands:
    - pip check
    - pytest --cov pytest_describe

about:
  home: https://github.com/pytest-dev/pytest-describe
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Describe-style plugin for py.test
  description: |
    pytest-describe is a plugin for pytest that allows tests to be written in arbitrary
    nested describe-blocks, similar to RSpec (Ruby) and Jasmine (JavaScript).
  dev_url: https://github.com/pytest-dev/pytest-describe
  doc_url: https://github.com/pytest-dev/pytest-describe/blob/main/README.md

extra:
  recipe-maintainers:
    - bollwyvl
