{% set name = "pytest-describe" %}
{% set version = "3.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace("-", "_") }}-{{ version }}.tar.gz
  sha256: 50e0b7f404decaeb1b5d7bca13cbe369208d1eeffafc2802663777b195f074ff

build:
  skip: true  # [py<39]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
    - uv-build >=0.9.4,<0.10.0
  run:
    - python
    - pytest >=6,<9

test:
  requires:
    - pytest-cov
    - pip
  source_files:
    - test
  imports:
    - pytest_describe
  commands:
    - pip check
    - pytest -ra -v --tb=short --cov pytest_describe

about:
  home: https://github.com/pytest-dev/pytest-describe
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Describe-style plugin for py.test
  description: |
    pytest-describe is a plugin for pytest that allows tests to be written in arbitrary
    nested describe-blocks, similar to RSpec (Ruby) and Jasmine (JavaScript).
  dev_url: https://github.com/pytest-dev/pytest-describe
  doc_url: https://github.com/pytest-dev/pytest-describe/blob/main/README.md

extra:
  recipe-maintainers:
    - bollwyvl
